pyExceptions/__init__.py,sha256=KaqcAKWcoMKTjcJYQwAZ-VbpPD7gn-b-2ymVlIVX7EY,3028
pyExceptions-0.1.12.dist-info/LICENSE.md,sha256=DF4r-Jbsz_ZASY4VjV0ZZVaaHYkH9a20BkVExpq8doE,10571
pyExceptions-0.1.12.dist-info/METADATA,sha256=TmgewndfL_7S5hlfJPUVUPTqi1eruMTwklpCIDtUv8k,2125
pyExceptions-0.1.12.dist-info/WHEEL,sha256=p46_5Uhzqz6AzeSosiOnxK-zmFja1i22CrQCjmYe8ec,92
pyExceptions-0.1.12.dist-info/top_level.txt,sha256=FCUx2KjHbxV3j3LdKBNNoUArrjEkFQTn9tzdqg_RCWs,13
pyExceptions-0.1.12.dist-info/RECORD,,
